# Generated by Django 6.0.1 on 2026-02-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=50)),
                ('client_last_name', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(help_text='Кратко съобщение към нашия детегледач')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='sitters.sitter')),
            ],
        ),
    ]
