# Generated by Django 6.0.1 on 2026-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=50)),
                ('client_last_name', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(help_text='Кратко съобщение към нашия детегледач')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
