# Generated by Django 6.0.1 on 2026-02-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('short_bio_introduction', models.TextField(help_text='Разкажи накратко за себе си!')),
                ('application_status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview stage'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
