# Generated by Django 6.0.1 on 2026-02-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='short_bio_introduction',
            field=models.TextField(help_text='Разкажете накратко за себе си!'),
        ),
    ]
