# Generated by Django 6.0.1 on 2026-02-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_first_name', models.CharField(max_length=50)),
                ('sitter_last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('experience', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(upload_to='sitters_photos')),
                ('services', models.ManyToManyField(related_name='sitters', to='services.servicegroup')),
            ],
        ),
    ]
