# Generated by Django 6.0.1 on 2026-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sitters_photos'),
        ),
    ]
